# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "mls-scraper"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_lambda.parameters]
warm_containers = "LAZY"

[dev.deploy.parameters]
stack_name = "mls-scraper"
resolve_s3 = true
s3_prefix = "mls-scraper"
resolve_image_repos = true
region = "us-west-2"
profile = "personal-anthony"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
